spring:
  mvc:
    servlet:
      path: /api
  datasource:
    driver-class-name:


# Redis
  data:
    redis:
      host: localhost
      port: 6379
      password:

    # MongoDB
    mongodb:
      uri: mongodb://root:rootpass@localhost:27017/chart?authSource=admin
      database: chart